# Generated by Django 4.2.1 on 2023-06-10 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='ser_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='ser_logo',
            field=models.FileField(default='', upload_to='images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'doc'])]),
        ),
        migrations.AddField(
            model_name='service',
            name='ser_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
