# Generated by Django 4.2.1 on 2023-06-10 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_remove_service_brief_remove_service_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('feature1', models.CharField(max_length=100)),
                ('feature2', models.CharField(max_length=100)),
                ('feature3', models.CharField(max_length=100)),
                ('feature4', models.CharField(max_length=100)),
                ('feature5', models.CharField(max_length=100)),
                ('feature6', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pic', models.FileField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
        ),
    ]
