# Generated by Django 4.2.1 on 2023-06-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Pricing',
        ),
    ]
