# Generated by Django 4.2.1 on 2023-06-10 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_rename_plans_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('avatar', models.FileField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'doc'])])),
            ],
        ),
    ]
