# Generated by Django 4.2.1 on 2023-06-11 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_testmonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'doc', 'jpg'])])),
            ],
        ),
        migrations.AlterField(
            model_name='testmonial',
            name='avatar',
            field=models.FileField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'doc', 'jpg'])]),
        ),
    ]
