# Generated by Django 4.2.1 on 2023-06-11 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_work_alter_testmonial_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('like', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('nav', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'doc', 'jpg'])])),
            ],
        ),
    ]
